import { initializeApp, applicationDefault } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
initializeApp({ credential: applicationDefault(), projectId: "hogaru-1" });
const db = getFirestore();
const eg = (await db.collection("expenses").get()).docs.map(d=>d.data());
console.log("egresos en producción:", eg.length);
console.log("  CON accountCode:", eg.filter(e=>e.accountCode).length);
console.log("  SIN accountCode:", eg.filter(e=>!e.accountCode).length, " ← el camino normal SÍ lo rellena al crear");
console.log("\nasientos de egreso en el libro:");
const led = (await db.collection("ledgerEntries").where("type","==","egreso").get()).docs.map(d=>d.data());
console.log("  total:", led.length, "· con accountCode:", led.filter(e=>e.accountCode).length, "· sin:", led.filter(e=>!e.accountCode).length);
